apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-api
  namespace: cicd-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-api
  template:
    metadata:
      labels:
        app: cicd-api
    spec:
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: cicd-api
          image: harbor.cicd.svc.cluster.local/cicd/cicd-api:2
          ports:
            - containerPort: 8080