apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-api
  namespace: cicd-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-api
  template:
    metadata:
      labels:
        app: cicd-api
    spec:
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: cicd-api
          image: 172.18.0.2:32000/cicd/cicd-api:11
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"